version: "3.9"

services:
  db:
    build: ./docker/mysql
    platform: linux/amd64
    container_name: mysqldb
    ports:
      - ${DB_PORT:-3306}:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - default

  php:
    build: ./docker/php
    container_name: "php-fpm"
    volumes:
      - ./src:/var/www
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: "web"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin
    container_name: "phpmyadmin"
    env_file:
      - .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - default

volumes:
  db-store:

networks:
  default:
    name: laravel-net
